[firebase]
type = "service_account"
apiKey = "AIzaSyB8W9bwAOTlXQPhZCOohLthUmGUnDkFCcc"
authDomain = "expense-tracker-9deb0.firebaseapp.com"
project_id = "expense-tracker-9deb0"
private_key_id = "eb82ba1415a782d8bb026297c9e4a2652ef029fd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCwGctRHBXO1j8H
8qCzdwg7pk5C564EqqDk0ihZRnaT5fD0e8Nt7Hx6Morb9K3hpsUV+La3i8JAe7GS
qwRQPOfHBeZpJoFKUryFsuf2Ymg1MnPJg2TiPGftOZz9hfcSxlGez5onxXeh9T6I
h10tBLNEh0WkoPM4iMVK2so4hiMMt0EY2rmaNqC3kxFGv5pw5+MsL9sagN13qveC
bbRRcuq9o/Y08axUGrwOCOj+NJ1OwA4gAluq7uX1zS/3wWiuADwW+ubjyBdI4AA1
63jO8TNba/r8F96GBAmcNTyde7pBfoTJvbOeOFi9pu/GQgai1RKF1Pl1h/cAvBfX
ZGafupo1AgMBAAECggEABLR7uSwN7RvOTVEPOBxLDQTxfFoiTR+d8t8mktQOIP94...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@expense-tracker-9deb0.iam.gserviceaccount.com"
client_id = "104123796436691609578"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40expense-tracker-9deb0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
